### ISSUE TITLE
Major UI Update 

### ISSUE THREAD

**Issue by sergi-s** [sergi-s/spelling-practice-2#10]
Major Update UI (FreeSpelling (not logged id) + RegularSpelling (logged in))
- Larger text box
- Display all user incorrect words with Blur/Un-blur feature.
- Clickable Shortcut info symbol which allows for hide/appear of shortcut info
- First Title header changed to new name "LexAI" + move position up
- Nav updated: Just login button. Remove Home & title -- Hopefully will make the page have no vertical overflow (page has no need to scroll down, we have enough space to showcase all our tools without scrolling so ensure page fits in any page resolutions without scrolling - adds simplicity and better user experience by removing un-needed feature)
- Gradient Background

**Comment by Stezzly** [comment]
All above features completed and seem to be working properly. Could do some minor tweaks but looks good.
Pushed to Stephen_Branch. Will finish rest of tweaks then discuss to merge to main @sergi-s
